#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityBrowserTile

#include "Basic.hpp"

#include "DiscoveryBrowserUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActivityBrowserTile.ActivityBrowserTile_C
// 0x0000 (0x1540 - 0x1540)
class UActivityBrowserTile_C final : public UFortActivityBrowserTile
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ActivityBrowserTile_C">();
	}
	static class UActivityBrowserTile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivityBrowserTile_C>();
	}
};

}

