#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActivityBrowserTile_Homebar_NEW_VM

#include "Basic.hpp"

#include "ActivityBrowserTile_Homebar_NEW_VM_classes.hpp"
#include "ActivityBrowserTile_Homebar_NEW_VM_parameters.hpp"


namespace SDK
{

// Function ActivityBrowserTile_Homebar_NEW_VM.ActivityBrowserTile_Homebar_NEW_VM_C.BndEvt__ActivityBrowserTile_Homebar_NEW_VM_WBP_BottomBarDecoyButton_SelectTouch_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTile_Homebar_NEW_VM_C::BndEvt__ActivityBrowserTile_Homebar_NEW_VM_WBP_BottomBarDecoyButton_SelectTouch_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTile_Homebar_NEW_VM_C", "BndEvt__ActivityBrowserTile_Homebar_NEW_VM_WBP_BottomBarDecoyButton_SelectTouch_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::ActivityBrowserTile_Homebar_NEW_VM_C_BndEvt__ActivityBrowserTile_Homebar_NEW_VM_WBP_BottomBarDecoyButton_SelectTouch_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTile_Homebar_NEW_VM.ActivityBrowserTile_Homebar_NEW_VM_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTile_Homebar_NEW_VM_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTile_Homebar_NEW_VM_C", "BP_OnItemSelectionChanged");

	Params::ActivityBrowserTile_Homebar_NEW_VM_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTile_Homebar_NEW_VM.ActivityBrowserTile_Homebar_NEW_VM_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UActivityBrowserTile_Homebar_NEW_VM_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTile_Homebar_NEW_VM_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTile_Homebar_NEW_VM.ActivityBrowserTile_Homebar_NEW_VM_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UActivityBrowserTile_Homebar_NEW_VM_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTile_Homebar_NEW_VM_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ActivityBrowserTile_Homebar_NEW_VM.ActivityBrowserTile_Homebar_NEW_VM_C.ExecuteUbergraph_ActivityBrowserTile_Homebar_NEW_VM
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTile_Homebar_NEW_VM_C::ExecuteUbergraph_ActivityBrowserTile_Homebar_NEW_VM(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTile_Homebar_NEW_VM_C", "ExecuteUbergraph_ActivityBrowserTile_Homebar_NEW_VM");

	Params::ActivityBrowserTile_Homebar_NEW_VM_C_ExecuteUbergraph_ActivityBrowserTile_Homebar_NEW_VM Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTile_Homebar_NEW_VM.ActivityBrowserTile_Homebar_NEW_VM_C.OnBroadcastToRowTileClicked
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTile_Homebar_NEW_VM_C::OnBroadcastToRowTileClicked(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTile_Homebar_NEW_VM_C", "OnBroadcastToRowTileClicked");

	Params::ActivityBrowserTile_Homebar_NEW_VM_C_OnBroadcastToRowTileClicked Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ActivityBrowserTile_Homebar_NEW_VM.ActivityBrowserTile_Homebar_NEW_VM_C.OnInputMethodChange
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        NewInputType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UActivityBrowserTile_Homebar_NEW_VM_C::OnInputMethodChange(ECommonInputType NewInputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ActivityBrowserTile_Homebar_NEW_VM_C", "OnInputMethodChange");

	Params::ActivityBrowserTile_Homebar_NEW_VM_C_OnInputMethodChange Parms{};

	Parms.NewInputType = NewInputType;

	UObject::ProcessEvent(Func, &Parms);
}

}

