#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BBE_GrindRailJump

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BBE_GrindRailJump.BBE_GrindRailJump_C
// 0x0000 (0x0080 - 0x0080)
class UBBE_GrindRailJump_C final : public UFortMobileActionButtonBehaviorExtension
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BBE_GrindRailJump_C">();
	}
	static class UBBE_GrindRailJump_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBBE_GrindRailJump_C>();
	}
};

}

