#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CrewSeasonLaunchScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CrewUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CrewSeasonLaunchScreen.CrewSeasonLaunchScreen_C
// 0x0018 (0x0540 - 0x0528)
class UCrewSeasonLaunchScreen_C final : public UCrewSeasonLaunchScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0528(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_Background_Blurred;                          // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USafeZone*                              SafeZone_0;                                        // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_CrewSeasonLaunchScreen(int32 EntryPoint);
	void OnDownloadBackgroundComplete(class UTexture2D* NewBackground);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CrewSeasonLaunchScreen_C">();
	}
	static class UCrewSeasonLaunchScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCrewSeasonLaunchScreen_C>();
	}
};

}

