#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Pawn_Parent

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Enum_NPC_AlertLevel_structs.hpp"
#include "FortniteAI_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "Struct_NPC_TargetSlots_structs.hpp"
#include "Enum_NPC_TargetSlots_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_Pawn_Parent.NPC_Pawn_Parent_C
// 0x0870 (0x3D90 - 0x3520)
class ANPC_Pawn_Parent_C : public AFortAIPawn
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x3520(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USoundLibraryComponent*                 SoundLibrary;                                      // 0x3528(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortPawnComponent_CustomDepth*         FortPawnComponent_CustomDepth;                     // 0x3530(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCapsuleComponent*                      WeaponCapsuleCollision;                            // 0x3538(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortTaggedNavFiltersComponent*         FortTaggedNavFilters;                              // 0x3540(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortActorComponent_Affiliation*        FortActorComponent_Affiliation;                    // 0x3548(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USoundLibraryComponent*                 SoundLibrary_Component;                            // 0x3550(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        MovementAudioComponent;                            // 0x3558(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNPC_VoiceComponent_C*                  NPC_VoiceComponent;                                // 0x3560(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        VOAudioComponent;                                  // 0x3568(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortWidgetComponent*                   NPCStatusWidget;                                   // 0x3570(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_ScaleMeshInOrOut_MeshScaleAlpha_9DAAC0B243D26E4160CEC3A458AE0E86; // 0x3578(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_ScaleMeshInOrOut__Direction_9DAAC0B243D26E4160CEC3A458AE0E86; // 0x357C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_357D[0x3];                                     // 0x357D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_ScaleMeshInOrOut;                         // 0x3580(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_NPC_RecentlyDamaged;                            // 0x3588(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	Enum_NPC_AlertLevel                           NPC_AlertLevel;                                    // 0x3590(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	Enum_NPC_AlertLevel                           NPC_AlertLevelPrevious;                            // 0x3591(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3592[0x6];                                     // 0x3592(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<Enum_NPC_AlertLevel, struct FGameplayTag> NPC_AlertLevelToTagMap;                           // 0x3598(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_StatusWidgetHealthBarDisabled;                 // 0x35E8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35E9[0x3];                                     // 0x35E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           GameplayCue_PickupGrabbed;                         // 0x35EC(0x0004)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	EFortRarity                                   NPC_BestLootRarityInInventory;                     // 0x35F0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_DebugPawn;                                     // 0x35F1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_ShowInventoryRarityVisuals;                    // 0x35F2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35F3[0x5];                                     // 0x35F3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        InventoryGlowDelay;                                // 0x35F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         NPC_NumberOfInventoryItemsToDeliverHF;             // 0x3600(0x0028)(Edit, BlueprintVisible)
	bool                                          NPC_SpawnInvisible;                                // 0x3628(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_ScaleMeshInOnSpawn;                            // 0x3629(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_362A[0x6];                                     // 0x362A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  TC_NPC_SpawnAbilityTag;                            // 0x3630(0x0020)(Edit, BlueprintVisible)
	struct FGameplayTagContainer                  TC_NPC_AlternateSpawnAbilityTag;                   // 0x3650(0x0020)(Edit, BlueprintVisible)
	bool                                          NPC_IsSpawning;                                    // 0x3670(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3671[0x7];                                     // 0x3671(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        NPC_OriginalGravityScale;                          // 0x3678(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               NPC_OriginalRotationRate;                          // 0x3680(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          NPC_HasPawnGoal;                                   // 0x3698(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3699[0x7];                                     // 0x3699(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 NPC_PawnGoalActor;                                 // 0x36A0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         NPC_NumberOfInventoryItemsToConsumeBeforeFullHF;   // 0x36A8(0x0028)(Edit, BlueprintVisible)
	bool                                          NPC_PawnIsDestroyingBuildingForNavigation;         // 0x36D0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36D1[0x7];                                     // 0x36D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         MaxIdleVODelay;                                    // 0x36D8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         MinIdleVODelay;                                    // 0x3700(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         NPC_DeathDropLootDelay;                            // 0x3728(0x0028)(Edit, BlueprintVisible)
	class FName                                   NPC_DeathDropLootTierGroupName;                    // 0x3750(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3754[0x4];                                     // 0x3754(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  NPC_DeathDropLootRequiredDamageTags;               // 0x3758(0x0020)(Edit, BlueprintVisible)
	struct FGameplayTagContainer                  NPC_DeathDropLootForbiddenDamageTags;              // 0x3778(0x0020)(Edit, BlueprintVisible)
	struct FGameplayTagContainer                  GrantStartingItemsAbilityTC;                       // 0x3798(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_HasItemInInventory;                            // 0x37B8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37B9[0x3];                                     // 0x37B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           VoiceTag_FullAlertIdle;                            // 0x37BC(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_Idle;                                     // 0x37C0(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_ReturnToIdle;                             // 0x37C4(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_LostTarget;                               // 0x37C8(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_Suspicious;                               // 0x37CC(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           VoiceTag_FullAlert;                                // 0x37D0(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37D4[0x4];                                     // 0x37D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FStruct_NPC_TargetSlots>        NPC_TargetSlotsHF;                                 // 0x37D8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_DamageCanCancelIntroPhase;                     // 0x37E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_37E9[0x7];                                     // 0x37E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagQuery                      TQ_NPC_DamageTagsThatCanCancelIntroPhase;          // 0x37F0(0x0048)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass*                                 GE_NPC_IntroPhaseBehaviorCooldown;                 // 0x3838(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  TC_IntroBehaviorActive;                            // 0x3840(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Debug_NPC_AlertLevelForced;                        // 0x3860(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_PawnCanInteractInternal;                       // 0x3861(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3862[0x6];                                     // 0x3862(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         NPC_PrimtiveDataFloatSetRandomlyInRange;           // 0x3868(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PrimtiveDataFloatIndexHF;                      // 0x3890(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PrimtiveDataFloatMinRangeHF;                   // 0x38B8(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PrimtiveDataFloatMaxRangeHF;                   // 0x38E0(0x0028)(Edit, BlueprintVisible)
	class AActor*                                 NPC_Leader;                                        // 0x3908(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, RepNotify, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           GameplayCue_LeaderSet;                             // 0x3910(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3914[0x4];                                     // 0x3914(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        NPC_Skeletal_Mesh_Index;                           // 0x3918(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             TamedSound;                                        // 0x3920(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        StateChangeSound;                                  // 0x3928(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         NPC_ShouldDespawnFromStormHF;                      // 0x3930(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_DespawnTimerHF;                                // 0x3958(0x0028)(Edit, BlueprintVisible)
	struct FGameplayTag                           NPC_DespawnGameplayTag;                            // 0x3980(0x0004)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3984[0x4];                                     // 0x3984(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           NPC_TestIsInSafeZoneTimer;                         // 0x3988(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           NPC_DespawnFromStormTimer;                         // 0x3990(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_isTryingToDespawn;                             // 0x3998(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3999[0x3];                                     // 0x3999(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           NPC_ResetIntroGameplayTags;                        // 0x399C(0x0004)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	double                                        SelectedPrimitiveDataFloat;                        // 0x39A0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           GameplayCue_Death;                                 // 0x39A8(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39AC[0x4];                                     // 0x39AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UMaterialInterface*>             OG_Materials;                                      // 0x39B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          NPC_Apply_GE_for_Swimming;                         // 0x39C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39C1[0x7];                                     // 0x39C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 NPC_GE_ClassToApplyForSwimming;                    // 0x39C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          Exit_Burst_GC;                                     // 0x39D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39D1[0x3];                                     // 0x39D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            NPC_GE_AppliedForSwimming;                         // 0x39D4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	class FName                                   GoalActorBBKey;                                    // 0x39DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           GameplayCueLureInterest;                           // 0x39E0(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39E4[0x4];                                     // 0x39E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                NPC_PreviousLureGoal;                              // 0x39E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Exit_Water;                                        // 0x39F0(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Enter_Water;                                       // 0x39F4(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         NPC_MaxDistanceFromDamagedNPCToDrawHeallthBarHF;   // 0x39F8(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_HealthBarHideTimeAfterDeathHF;                 // 0x3A20(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PlayEffectWhenLuredHF;                         // 0x3A48(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_PawnCanInteractHF;                             // 0x3A70(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_AllowInteractOnlyWhenUnawareHF;                // 0x3A98(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_AllowInteractWhenHasLeaderHF;                  // 0x3AC0(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         NPC_AllowDrownInShallowWaterHF;                    // 0x3AE8(0x0028)(Edit, BlueprintVisible)
	bool                                          NPC_IsInventoryInitialized;                        // 0x3B10(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B11[0x3];                                     // 0x3B11(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LeaderClearedCueDelay;                             // 0x3B14(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           GameplayCue_LeaderCleared;                         // 0x3B18(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          isGCForLeaderSetLooping;                           // 0x3B1C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B1D[0x3];                                     // 0x3B1D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           NPC_DeathByStormTag;                               // 0x3B20(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_TryDespawnAbility;                             // 0x3B24(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B25[0x3];                                     // 0x3B25(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            GeOutsideSafeZoneDamageHandle;                     // 0x3B28(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsGEStormDamageInit;                               // 0x3B30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_MeshScalingInProgress;                         // 0x3B31(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_DisableCapsuleOverlapsWhenScalingOut;          // 0x3B32(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B33[0x5];                                     // 0x3B33(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                NPC_OriginalMeshScale;                             // 0x3B38(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              NPCScaleMeshInCompleted;                           // 0x3B50(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              NPCScaleMeshOutCompleted;                          // 0x3B60(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          NPC_CanDropLoot;                                   // 0x3B70(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B71[0x7];                                     // 0x3B71(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         NPC_StaleDespawnTestDistance_HF;                   // 0x3B78(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         NPC_StaleDespawnTimeThreshold_HF;                  // 0x3BA0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                        NPC_LastNonStaleCheckTime;                         // 0x3BC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bCanBeDamagedByNullInstigator;                     // 0x3BD0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsEnteringWater;                                   // 0x3BD1(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BD2[0x6];                                     // 0x3BD2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class AActor* AIPawn, class AFortPlayerPawn* InteractingPlayerPawn)> NPCPawnInteractWithDispatcher; // 0x3BD8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          NPCDynamicBlockConversionOnInteract;               // 0x3BE8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NPC_TempInteractOverride;                          // 0x3BE9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BEA[0x6];                                     // 0x3BEA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             HeadShot_Sound;                                    // 0x3BF0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FName                                   Headshot_FX_Socket;                                // 0x3BF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseHeadShotFX;                                     // 0x3BFC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BFD[0x3];                                     // 0x3BFD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  TC_WeaponTypesAllowedForHeadshotFX;                // 0x3C00(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          AllowHeadshot;                                     // 0x3C20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C21[0x7];                                     // 0x3C21(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        AdditiveHitReactRetriggerDelay;                    // 0x3C28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           Additive_Hit_React_Montage;                        // 0x3C30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Death_Normal_Sound;                                // 0x3C38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        HeadshotFXEmitterTemplate;                         // 0x3C40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  Sound_Library_Collection_Tags;                     // 0x3C48(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTagContainer                  Sound_Library_Default_Tags;                        // 0x3C68(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTagContainer                  Sound_Library_Alert_Tags;                          // 0x3C88(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTagContainer                  Sound_Library_Aggressive_Tags;                     // 0x3CA8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class USoundLibrary*>                  SoundLibs_Default;                                 // 0x3CC8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class USoundLibrary*>                  SoundLibs_Alert;                                   // 0x3CD8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USoundLibrary*                          CurrentSoundLib;                                   // 0x3CE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class USoundLibrary*>                  SoundLibs_Aggressive;                              // 0x3CF0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class USoundLibrary*>                  SoundLibs_Foley;                                   // 0x3D00(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class USoundLibrary*>                  SoundLibs_Foley_Water;                             // 0x3D10(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USoundLibrary*                          CurrentFoleyLib;                                   // 0x3D20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        Custom_Depth_Update_Rate;                          // 0x3D28(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Class_0;                                           // 0x3D30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class UGameplayEffect>            GE_Converted;                                      // 0x3D38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle            GE_Converted_Handle;                               // 0x3D40(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        NPC_Death_Time;                                    // 0x3D48(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	float                                         ScaleMeshInOrOutPlayRate;                          // 0x3D50(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AllowSkipScaleOutIfNotRecentlyRendered;            // 0x3D54(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D55[0x3];                                     // 0x3D55(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(Enum_NPC_AlertLevel NPC_Alert_Level)> NPCAlertLevelUpdated;        // 0x3D58(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FGameplayTagContainer                  GameplayTagsToBlockHitReact;                       // 0x3D68(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTag                           GCInstantDeathTag;                                 // 0x3D88(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void NPC_AlertLevelChangedServer(Enum_NPC_AlertLevel NPCAlertLevel);
	void NPC_CanBeInteractedWith(bool* CanInteract);
	void NPC_LeaderSet(bool Success_, class AActor* Leader, EUnconvertReason UnconvertReason);
	void NPC_PickupGrabbed_Destroyed(class AActor* ActorGrabbed);
	void NPC_UpdateHealthBarComponentVisibility();
	void On_NPC_PawnInteractedWith(class AActor* AIPawn, class AFortPlayerPawn* InteractingPlayerPawn);
	void OnDamagePlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnDeathServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void OnPawnHealthChanged_Event_0();
	void Play_Water_Splash_at_Water_Surface(class AFortWaterBodyActor* Water_Body, bool Enter_Water_0);
	void PlayAdditiveHitReacts(const struct FVector& Hit_Direction, class UAnimMontage* Anim_Montage);
	void PlayStateChangeAudio(Enum_NPC_AlertLevel Index_0);
	void ReceiveBeginPlay();
	void TryShowHealthBar();
	void ExecuteUbergraph_NPC_Pawn_Parent(int32 EntryPoint);
	void Orphaned(bool* IsOrphaned, class AFortPawn** AttachedPawn);
	void RemoveLibraryCollection();
	void Check_Tag(const struct FGameplayTagContainer& Tag_Container, bool* ShouldDefault);
	void UpdateSoundLibraryCollection(bool AddLibraries, bool* ValidLibraries);
	void OnRep_NPC_Death_Time();
	void IsConverted(bool* IsConverted_0);
	void NPC_GhostCollisionSettings(bool NoCollisionForRanged, bool NoCollisionForMelee, bool NoCollisionForProjectiles, bool OnlyOverlapCollisionForPawns);
	bool CanUpdateSoundLib(const TArray<class USoundLibrary*>& TargetArray);
	void NPC_DamageRemovesIdlePhaseTagGE();
	void GetSoundFoleyLibrary();
	void NPC_CheckForDespawnIfStaleToPlayers(class AFortPlayerPawn* ClosestFortPlayerPawn);
	void NPC_SetCanDropLoot(bool CanDropLoot);
	void NPC_GetSafeZonePhase(int32* SafeZonePhase);
	void OnRep_NPC_Leader();
	void ResetMaterialFromDeath();
	void OnRep_SelectedPrimitiveDataFloat();
	void CheckSoundLibraryRemoved(TArray<class USoundLibrary*>& Libraries);
	void CheckSoundLibraryAdded(TArray<class USoundLibrary*>& Libraries);
	void UpdateSoundLibrary(Enum_NPC_AlertLevel Alert_Level);
	void NPC_ClearOutTargetSlots();
	void NPC_UpdateInteract(bool CanInteract, bool* EnabledInteract);
	void NPC_HasLeader_(bool* HasLeader_, class AActor** Leader);
	void NPC_SetLeader(class AActor* Leader, bool* Success_, class AActor** LeaderSet);
	void NPC_AttemptToSetLeader(class AActor* PossibleLeader, EUnconvertReason UnconvertReason);
	void SetPrimitiveDataFloat();
	void SelectPrimitiveDataFloat();
	void StoreOriginalGravityAndRotation();
	void NPC_DisableIntroPhaseBehavior();
	void NPC_DamageAttemptDisableIntroPhaseBehavior(const struct FGameplayTagContainer& DamageTags);
	void NPC_TargetSlotIsUsingOverride(Enum_NPC_TargetSlots TargetSlotType, class AActor* TargetWeWantToSlotOnto, bool* Override);
	void NPC_TargetSlotInfo(Enum_NPC_TargetSlots TargetSlotType, class AActor* TargetWeWantToSlotOnto, int32* TargetSlotCount, int32* TargetSlotMax, int32* NPC_TargetSlotsRequired, bool* TargetSlotsMaxOrMore, bool* TargetSlotCountIsExactlyMax, bool* NPC_IsTargetSlotOwner, bool* NPC_HasSpaceToSlotOnTarget, Enum_NPC_TargetSlots* TargetSlotTypeOut, class UClass** TargetSlotCountingGE, struct FScalableFloat* AI_TargetSlotSizeHF, struct FScalableFloat* AI_TargetSlotDurationHF, class UClass** TargetSlotOverrideGE, class UClass** TargetSlotOwnerGE, class UClass** TargetSlotCountingMaxedGE);
	void NPC_CheckIsInSafeZone(bool* TestSucceeded, bool* isInSafeZone);
	void NPC_HandleAlertLevelVoice();
	void NPC_TryToDropLootOnDeath(const struct FGameplayTagContainer& DamageTags, bool* CanDropLoot);
	void NPC_ApplyGameplayEffectWithMMRScaling(class AActor* Actor, class UClass* GE_Class);
	void NPC_SetLootCollectionPhaseCompleteToBlackboard(bool LootCollectionPhaseComplete);
	void NPC_ResetOriginalRotationRate();
	void NPC_ResetOriginalGravityScale();
	void NPC_SetReturnGatheredLootToBlackboard();
	void NPC_GetScalableFloatHotfixValue(const struct FScalableFloat& ScalableFloatHotfix, double AtLevel, bool* AsBool, int32* AsIntRounded, double* AsFloat);
	void NPC_ScalableFloatIsValid(const struct FScalableFloat& ScalableFloat, bool* Valid);
	void NPC_PickupDropped(class AFortPickup* FortPickupDropped);
	void NPC_PickupGrabbed(class AFortPickup* FortPickupGrabbed);
	void OnRep_NPC_BestLootRarityInInventory();
	void NPC_SendGameplayCuePickupGrabbed();
	void NPC_PawnDebugMessage(const class FString& String, bool OnlyWhenDebug);
	void NPC_GetInventoryInformation(bool* HasItemInInventory, int32* TotalNumberOfInventoryItems, int32* LastInventoryItemIndex, bool* HasEnoughItemsToDeliver, bool* ConsumedEnoughItemsToBeConsideredFull);
	void NPC_SetBestLootRarityInInventory(EFortRarity* NPC_BestLootRarityInInventory_0);
	void OnRep_NPC_AlertLevel();
	void NPC_GetAlertLevelInfo(Enum_NPC_AlertLevel* AlertLevel, struct FGameplayTag* AlertLevelTag, bool* ValidDataFound);
	void NPC_ApplyRecentlyDamagedTagGE(class UClass* RecentlyDamagedOverride);
	bool ShouldUpdateSkeletalMesh();
	void UserConstructionScript();
	void Timeline_ScaleMeshInOrOut__FinishedFunc();
	void Timeline_ScaleMeshInOrOut__UpdateFunc();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void WidgetVisibilityChanged(bool bVisible);
	void NPC_ParentLaunchVehicle(class AActor* Vehicle, const struct FVector& Velocity);
	void TestLoot();
	void ReceivePossessed(class AController* NewController);
	void RequestUpdateNPCAlertLevel(Enum_NPC_AlertLevel NPC_AlertLevel_0);
	void NPCAlertLevelChangedClient(Enum_NPC_AlertLevel NPC_AlertLevel_0);
	void NPC_InitializeIdleVO();
	void TriggerIdleVO();
	void NPCEnableHealthBars();
	void NPCDisableHealthBars();
	void Debug_AlertLevel_ForceLevel(Enum_NPC_AlertLevel NewNPC_AlertLevel);
	void Debug_AlertLevel_ClearDebug();
	void Debug_ForceAlertLevel_Invalid();
	void Debug_ForceAlertLevel_Unaware();
	void Debug_ForceAlertLevel_NA();
	void Debug_ForceAlertLevel_Alerted();
	void Debug_ForceAlertLevel_Aggressive();
	void HandleInteracts();
	void NPC_Pawn_Interact(class AFortAIPawn* AI, class AFortPlayerController* InteractingPlayerController, EInteractionBeingAttempted InteractionBeingAttempted);
	void OnBeginDeepWaterInteraction(const struct FVector& WaterSurfaceLocation, float WaterDepth);
	void GrantStartingItems();
	void TestIsInSafeZone();
	void TryToDespawnDueToStorm(bool Reset_Timer);
	void InitializeTestInSafeZone();
	void OnDamageServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void DespawnDueToStorm();
	void TriggerDeathFX();
	void OnEndDance();
	void OnBeginDance();
	void End_Music_Tracker();
	void BeginMusicTracker();
	void StopUpdatingHealthBarWidget();
	void RemoveSoundSystemLibraries();
	void AddSoundSystemLibraries();
	void InitializeInventory();
	void StartUpdatingHleathBarWidget();
	void OnEnteredWaterBody(class AFortWaterBodyActor* WaterBody, bool bIsFirstBody);
	void OnExitedWaterBody(class AFortWaterBodyActor* WaterBody, bool bIsLastBody);
	void LuredOnServer(Enum_NPC_AlertLevel AlertLevel);
	void LuredInterest();
	void PlayEnterWaterSplash(class AFortWaterBodyActor* Water_Body);
	void PlayExitWaterSplash(class AFortWaterBodyActor* Water_Body);
	void TryWaterInteractionDrown();
	void StopTestingIsInSafeZone();
	void NPCScaleMeshIn();
	void NPCScaleMeshOut();
	void TriggerDespawnAbility();
	void NPC_MulticastGameplayCueDeath();
	void UpdateSoundLibFoley();
	void AdditiveHitReactDelay();
	void UpdateCustomDepth();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPC_Pawn_Parent_C">();
	}
	static class ANPC_Pawn_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_Pawn_Parent_C>();
	}
};

}

