#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseNPC

#include "Basic.hpp"

#include "EntityCore_classes.hpp"
#include "VerseFortnite_classes.hpp"
#include "VerseAIBase_0_classes.hpp"


namespace SDK
{

// Class VerseNPC.InventoryComponentBase
// 0x0040 (0x0098 - 0x0058)
class UInventoryComponentBase : public UEntityComponent
{
public:
	uint8                                         Pad_58[0x28];                                      // 0x0058(0x0028)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortInventory*                         CachedFortInventory;                               // 0x0080(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class AFortPawn*                              CachedFortPawn;                                    // 0x0088(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UBlackboardComponent*                   CachedBlackboardComponent;                         // 0x0090(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"InventoryComponentBase">();
	}
	static class UInventoryComponentBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInventoryComponentBase>();
	}
};

// Class VerseNPC.LeashComponentBase
// 0x0000 (0x0070 - 0x0070)
class ULeashComponentBase : public UAIComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LeashComponentBase">();
	}
	static class ULeashComponentBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULeashComponentBase>();
	}
};

// Class VerseNPC.NPCPerceptionComponentBase
// 0x0000 (0x0080 - 0x0080)
#pragma pack(push, 0x1)
class alignas(0x08) UNPCPerceptionComponentBase : public UAIPerceptionComponentBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NPCPerceptionComponentBase">();
	}
	static class UNPCPerceptionComponentBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNPCPerceptionComponentBase>();
	}
};
#pragma pack(pop)

}

