#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FortFrontendSurvivorTier

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_FortFrontendSurvivorTier.W_FortFrontendSurvivorTier_C
// 0x0008 (0x02D8 - 0x02D0)
class UW_FortFrontendSurvivorTier_C final : public UFortFrontendSurvivorTier
{
public:
	class UW_SurvivorTierBadge_C*                 W_SurvivorTierBadgeOld;                            // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_FortFrontendSurvivorTier_C">();
	}
	static class UW_FortFrontendSurvivorTier_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_FortFrontendSurvivorTier_C>();
	}
};

}

